### ISSUE TITLE
Allow for adjusting the height of the AZ

### ISSUE THREAD

**Issue by ruilvo** [arkorobotics/azgen-web#21]
Hello!

Thanks for your work!

It would be great if it was possible to select the height for computing the activation zone. 

In some associations, like here in the CT association, we use 25m as the vertical distance for the AZ. 

So if it was possible to add a box for the vertical distance of the AZ (and add that to the backend API, I know...) and get results with that extra customization it would be invaluable for us.

Thank you,
Rui, a.k.a CT7ALW

**Comment by arkorobotics** [comment]
Hello Rui,

Thanks for writing in! The activation zone generator uses [25 meters of vertical distance](https://github.com/arkorobotics/azgen-web/blob/main/src/App.vue#L458) from the summit per [SOTA rules](https://sotastore.blob.core.windows.net/docs/SOTA-General-Rules-June-2022.pdf). I'm not aware of any exceptions to this, so the system should work for the CT association. Do you have any examples where it doesn't work?

**Comment by ruilvo** [comment]
Nevermind, in your website it says that the "AZ is not definitive and is estimated using 30m DEM. " And my eyes just read that as 30m being the vertical distance. Nevermind that. It's the resolution of the terrain model, of course.

Sorry, thanks.
